# Generated by Django 2.1.5 on 2023-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.CharField(default='name name', max_length=128),
        ),
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateField(max_length=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default='a sentence'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
